BLOCK_SITE: []
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK:
- link: https://www.fanyiming.life/link/
  theme: butterfly
OUTDATE_CLEAN: 100
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: ''
  list:
  - - "\u8D30\u7339\u306E\u5C0F\u7A9D"
    - https://noionion.top/
    - https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg
  - - "Akilar\u306E\u7CD6\u679C\u5C4B"
    - https://akilar.top/
    - https://akilar.top/images/headimage.png
  - - elizen
    - https://elizen.me/
    - https://akilar.top/images/headimage.png
    - hello.xml
  - - "\u962E\u4E00\u5CF0\u7684\u7F51\u7EDC\u65E5\u5FD7"
    - http://www.ruanyifeng.com/
    - https://www.ruanyifeng.com/blog/images/person_shot.jpg
    - /blog/atom.xml
  - - "\u571F\u6728\u575B\u5B50"
    - https://feeds.feedburner.com/
    - https://cravatar.cn/avatar/a4368b0f22f9820265d7d2431addc8da?s=120&d=retro&r=g
    - /tumutanzi
  - - "\u9022\u91D1\u5409"
    - https://jinjipang.com/
    - https://jinjipang.com/cn/post/2021-07-08/images/profile.jpg
    - ''
  - - "\u98DF\u706F\u9B3C"
    - https://shidenggui.com/
    - https://avatars.githubusercontent.com/u/5035364?v=4
    - /feeds
